#user and passwords is on env file, be sure you'd follow README instructions
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    ports:
      - '5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}'
      - 'RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}'
    ports:
      - '5672'
  n8n:
    image: n8nio/n8n
    environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_PORT=5432
    - DB_POSTGRESDB_DATABASE=mydatabase 
    - DB_POSTGRESDB_USER=${N8N_USER}
    - DB_POSTGRESDB_PASSWORD=${N8N_PASSWORD} 
    depends_on:
      - postgres
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./uploads:/home/node/uploads

volumes:
  n8n_data:
    driver: local
  rabbitmq_data:
  postgres_data: